image: node

stages:
  - deploy

deploy:
  stage: deploy
  type: deploy
  image : ruby:2.2
  script:
    - apt-get update -qy
    - apt-get install -yqq ruby ruby-dev nodejs --silent
    - gem install dpl
    - dpl --provider=heroku --app=kanmu --api-  key=$HEROKU_TOKEN
  when: manual
  only:
    - master
